# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_debut', models.DateTimeField(verbose_name=b'date de debut')),
                ('date_fin', models.DateTimeField(verbose_name=b'date de fin')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ressource_type', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('capacite', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Salle'),
        ),
    ]
